// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs1qhqX6CWy5SK5lTd5_xKB-jvlzVdW2c',
    appId: '1:914489466249:web:ec8106f7b42fe9b8061558',
    messagingSenderId: '914489466249',
    projectId: 'crewx-1',
    authDomain: 'crewx-1.firebaseapp.com',
    storageBucket: 'crewx-1.firebasestorage.app',
    measurementId: 'G-SW59V0M331',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaIjFerDYprQSVQaPMfgRJGBB0hDDPhsc',
    appId: '1:914489466249:android:a7d72cebc450ed75061558',
    messagingSenderId: '914489466249',
    projectId: 'crewx-1',
    storageBucket: 'crewx-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmgAbEOwyI0nFHogxnFFTBNFlP8RwM60g',
    appId: '1:914489466249:ios:a4f0d611ab7801c5061558',
    messagingSenderId: '914489466249',
    projectId: 'crewx-1',
    storageBucket: 'crewx-1.firebasestorage.app',
    iosBundleId: 'com.shubhampandya.crewx.crewxPartner',
  );

}